version: "3.5"

# make sure that docker machine has enough memory to run the cluster.
# setting it up to 4GB seems to work.

services:

  cassandra3:
    image: cassandra:4.1.0
    container_name: cassandra
    mem_limit: 2g
    volumes:
      - "cassandra_data_3:/var/lib/cassandra"
    environment:
      - "CASSANDRA_BROADCAST_ADDRESS=192.168.0.13"
      - "CASSANDRA_SEEDS=192.168.0.11"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
#      needed for setting up custom cluster name
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
## Port nur für Public 
    ports:
       - "9042:9042"
       - "7001:7001"
       - "7000:7000"
       - "7199:7199"
       - "9160:9160"
    restart: always

networks:
  default:
    name: cassandra-docker
    external: true

volumes:
  cassandra_data_3:
