version: "3.3"

# make sure that docker machine has enough memory to run the cluster.
# setting it up to 4GB seems to work.

services:

  cassandra2:
    image: cassandra:4.1.0
    mem_limit: 2g
    volumes:
      - "cassandra_data_2:/var/lib/cassandra"
    environment:
      - "CASSANDRA_SEEDS=cassandra1"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
#      needed for setting up custom cluster name
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    restart: always

  #cassandra3:
  #  image: cassandra:4.1.0
  #  mem_limit: 2g
  #  volumes:
  #    - "cassandra_data_3:/var/lib/cassandra"
  #  environment:
  #    - "CASSANDRA_SEEDS=cassandra1"
  #    - "CASSANDRA_CLUSTER_NAME=Test Cluster"
# #     needed for setting up custom cluster name
  #    - "CASSANDRA_DC=se1"
  #    - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
##
  #  restart: always

networks:
  default:
    name: cassandra-docker
    external: true

volumes:
  cassandra_data_2:
  cassandra_data_3:
