version: "3.5"

services:

  cassandra2:
    image: cassandra:4.1.0
    mem_limit: 2g
    container_name: cassandra
    volumes:
      - "cassandra_data_2:/var/lib/cassandra"
    environment:
      - "CASSANDRA_BROADCAST_ADDRESS=192.168.0.12"
      - "CASSANDRA_SEEDS=192.168.0.11,192.168.0.12,192.168.0.13"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"

##  Replace Node: 
##  Diese ENV ist zu setzen wenn Node zerstört wurde.
##  Sind alle Daten auf dem alten Nodes verloren, 
##  muss dieser neue Node neu installiert werden und den alten Node mit der selben IP Adress ersetzen.
##  Dabei muss die ENV JVM_EXTRA_OPTS bei erstmaligem start gesetzt werden. 
#
#      - "JVM_EXTRA_OPTS=-Dcassandra.replace_address_first_boot=192.168.0.12  -Dcassandra.allow_unsafe_replace=true"



    ports:
       - "9042:9042"
       - "7001:7001"
       - "7000:7000"
       - "7199:7199"
       - "9160:9160"
    restart: always

networks:
  default:
    name: cassandra-docker
    external: true

volumes:
  cassandra_data_2:

